run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - misspell
    - unconvert
    - unused
    - staticcheck
    - gosimple
  disable:
    - errcheck  # Temporarily disabled due to extensive legacy code issues

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true